import { documentPage, articleCard, arrow } from './site.mjs';
import { faq } from '../content/faq.mjs';

export function homePage(logo, articles) {
  const products = [
    { file: 'mrpj-mramor.webp', width: 361, title: 'Mramorování', text: 'Kresba, která se neopakuje.', alt: 'Mramorovaná žebrovaná svíčka MRPJ s víčkem' },
    { file: 'mrpj-pastel.webp', width: 360, title: 'Pastelové tóny', text: 'Jemná barva. Výrazný tvar.', alt: 'Zelená a růžová žebrovaná nádoba MRPJ' },
    { file: 'mrpj-barvy.webp', width: 513, title: 'Hra barev', text: 'Malý detail pro každý den.', alt: 'Výběr barevných svíček a nádob MRPJ ve dvou fotografiích' },
  ];
  return documentPage({ home: true, title: 'MRPJ — Svíčky a nádoby s vlastním rukopisem', description: 'Rodinná tvorba MRPJ. Ručně vyráběné nádoby, svíčky ze sójového vosku a vlastní rukopis. Poznej naši tvorbu i péči o svíčky.', body: `<main id="obsah" tabindex="-1">
  <section id="uvod" class="hero" aria-labelledby="hero-title"><div class="hero-mark">${logo}</div><div class="hero-content container"><p class="eyebrow">MRPJ · RUČNÍ TVORBA</p><h1 id="hero-title">Malý plamen.<br />Velká chvíle klidu.</h1><p class="hero-description">Svíčky ze sójového vosku.<br />Nádoby, které mají vlastní rukopis.</p><a class="hero-link" href="#svicky">Prohlédnout tvorbu <span aria-hidden="true">↓</span></a></div><span class="hero-note" aria-hidden="true">Vytvořeno rukama. Pro tvoje chvíle.</span></section>
  <section id="svicky" class="collection section container" aria-labelledby="collection-title"><div class="section-heading"><p class="eyebrow">01 / TVORBA MRPJ</p><h2 id="collection-title">Každý kousek<br />má svou linku.</h2><p>Jednou jemná, podruhé nepravidelná. V barvě, kresbě i tvaru hledáme to, co dělá naše výrobky našimi.</p></div><div class="collection-grid">${products.map((product, i) => `<figure class="collection-card"><a class="photo-link" href="/images/${product.file}" data-photo="${product.file}" data-title="${product.title}" aria-label="Prohlédnout fotografii: ${product.title}"><span class="photo-image"><img src="/images/${product.file}" alt="${product.alt}" width="${product.width}" height="640" loading="lazy" /></span><span class="photo-action"><span>0${i + 1} / PROHLÉDNOUT</span><span aria-hidden="true">+</span></span></a><figcaption><h3>${product.title}</h3><p>${product.text}</p></figcaption></figure>`).join('')}</div></section>
  <section id="pribeh" class="story" aria-labelledby="story-title"><img class="story-line" src="/brand/motif-j.svg" alt="" aria-hidden="true" loading="lazy" /><div class="container story-grid"><div class="story-copy"><p class="eyebrow">02 / NAŠE RUCE. NÁŠ RUKOPIS.</p><h2 id="story-title">Začíná to nápadem.<br />Končí to u tebe.</h2><p>MRPJ je naše rodinná značka svíček a designových nádob. Baví nás projít celou cestu — od tvaru nádoby a výběru barev až po nalévání sójového vosku.</p><p>Někdy vznikne jemný pastel, jindy mramorová kresba nebo výrazná barva. Společné mají jedno: naše ruce a radost z tvoření.</p><p class="editorial">Malé věci.<br />Osobní vztah.</p><a class="text-link" href="#kontakt">Poznejme se ${arrow}</a></div><figure class="story-visual"><img src="/images/mrpj-vyroba.webp" alt="Nalévání vosku při skutečné výrobě MRPJ" width="360" height="640" loading="lazy" /><figcaption>POHLED DO NAŠÍ VÝROBY / MRPJ</figcaption></figure></div></section>
  <section id="cteni" class="reading section container" aria-labelledby="reading-title"><div class="section-heading"><p class="eyebrow">03 / MALÉ ČTENÍ</p><h2 id="reading-title">Ke svíčce patří<br />i trocha péče.</h2><p>O materiálu, dřevěném knotu a chvílích s plamenem. Všechno důležité najdeš přímo tady u nás.</p></div><div class="reading-grid">${articles.map(articleCard).join('')}</div></section>
  <section id="faq" class="faq section container" aria-labelledby="faq-title"><div class="faq-intro"><p class="eyebrow">04 / DOBRÉ VĚDĚT</p><h2 id="faq-title">Možná tě<br />zajímá…</h2><p>Pár odpovědí, než si zapálíš.</p></div><div class="faq-list">${faq.map(item => `<details><summary>${item.question}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>${item.answer}</p><a class="text-link" href="${item.link}">${item.label} ${arrow}</a></div></details>`).join('')}</div></section>
  </main><dialog id="photo-dialog" aria-labelledby="photo-title"><div class="dialog-heading"><div><p class="eyebrow">VLASTNÍ TVORBA MRPJ</p><h2 id="photo-title">Fotografie MRPJ</h2></div><button class="icon-button" id="close-dialog" type="button" autofocus aria-label="Zavřít fotografii">×</button></div><img id="dialog-photo" alt="" /><p class="dialog-caption">Z naší rodinné tvorby.</p></dialog>` });
}
