import { documentPage, articleCard, arrow } from './site.mjs';
import { faq } from '../content/faq.mjs';

export function homePage(logo, articles, signature) {
  const products = [
    { name: 'mrpj-svicky-barvy', width: 1600, height: 2133, title: 'Hra barev', text: 'Barevné nádoby, dřevěný knot a klidný plamen.', alt: 'Barevné svíčky MRPJ s dřevěným knotem v žebrovaných nádobách: žlutá, oranžová, světle růžová, modrá, korálová a mátová', position: 'center 55%' },
    { name: 'mrpj-mramor', width: 1600, height: 2133, title: 'Mramorování', text: 'Kresba, která se neopakuje.', alt: 'Mramorovaná nádoba MRPJ v černé a broskvové barvě na oválném podnosu', position: 'center 40%' },
    { name: 'mrpj-vlny', width: 1512, height: 2016, title: 'Barevné vlny', text: 'Každá vlna je jiná.', alt: 'Tři nádoby MRPJ s kresbou fialových, žlutých a modrých vln a vizitka MRPJ', position: 'center 62%' },
    { name: 'mrpj-geometrie', width: 1512, height: 2016, title: 'Geometrie', text: 'Hrany, které chytají světlo.', alt: 'Mátově bílá geometrická nádoba MRPJ vedle bílého květináče s vřesem a podnosu', position: 'center 48%' },
    { name: 'mrpj-pastel-tecky', width: 1512, height: 2016, title: 'Jemný pastel', text: 'Růžová s drobnými tečkami.', alt: 'Růžový květináč MRPJ s drobnými tečkami na podmisce, vedle vřes a vizitka MRPJ', position: 'center 50%' },
    { name: 'mrpj-zelena-par', width: 1512, height: 2016, title: 'Sytá zelená', text: 'Čistý tvar. Výrazný tón.', alt: 'Dvě zelené nádoby MRPJ na oválném podnosu s vizitkou MRPJ', position: 'center 55%' },
    { name: 'mrpj-zluta-oranzova', width: 1324, height: 2014, title: 'Slunečné tóny', text: 'Žlutá a oranžová vedle sebe.', alt: 'Žlutá hladká a oranžová žebrovaná nádoba MRPJ s vizitkou MRPJ', position: 'center 45%' },
    { name: 'mrpj-modra-cervena', width: 1512, height: 2016, title: 'Žebrování', text: 'Jemné linky po obvodu.', alt: 'Modrá žebrovaná, béžová a červená nádoba MRPJ s vizitkou MRPJ', position: 'center 68%' },
  ];
  return documentPage({ home: true, signature, title: 'MRPJ — Svíčky a nádoby s vlastním rukopisem', description: 'Rodinná tvorba MRPJ. Ručně vyráběné nádoby, svíčky ze sójového vosku a vlastní rukopis. Poznej naši tvorbu i péči o svíčky.', body: `<main id="obsah" tabindex="-1">
  <section id="uvod" class="hero" aria-labelledby="hero-title"><div class="hero-mark">${logo}</div><div class="hero-content container"><p class="eyebrow">MRPJ · RUČNÍ TVORBA</p><h1 id="hero-title">Malý plamen.<br />Velká chvíle klidu.</h1><p class="hero-description">Svíčky ze sójového vosku.<br />Nádoby, které mají vlastní rukopis.</p><a class="hero-link" href="#svicky">Prohlédnout tvorbu <span aria-hidden="true">↓</span></a></div><span class="hero-note" aria-hidden="true">Vytvořeno rukama. Pro tvoje chvíle.</span></section>
  <section id="svicky" class="collection section container" aria-labelledby="collection-title"><div class="section-heading"><p class="eyebrow">01 / TVORBA MRPJ</p><h2 id="collection-title">Každý kousek<br />má svou linku.</h2><p>Jednou jemná, podruhé nepravidelná. V barvě, kresbě i tvaru hledáme to, co dělá naše výrobky našimi.</p></div><div class="collection-grid">${products.map((product, i) => `<figure class="collection-card${i === 0 ? ' is-feature' : ''}"><a class="photo-link" href="/images/${product.name}.webp" data-photo="${product.name}.webp" data-title="${product.title}" aria-label="Prohlédnout fotografii: ${product.title}"><span class="photo-image"><img src="/images/${product.name}-800.webp" srcset="/images/${product.name}-800.webp 800w, /images/${product.name}.webp ${product.width}w" sizes="(min-width: 1024px) ${i === 0 ? '46vw' : '22vw'}, (min-width: 768px) 44vw, 80vw" alt="${product.alt}" width="${product.width}" height="${product.height}" loading="lazy" style="--photo-position: ${product.position}; --photo-scale: ${product.scale ?? 1}" /></span></a><figcaption><span class="card-index">0${i + 1}</span><div class="card-text"><h3>${product.title}</h3><p>${product.text}</p></div><span class="card-plus" aria-hidden="true">+</span></figcaption></figure>`).join('')}<a class="collection-more" href="https://www.instagram.com/mrpjcz/" target="_blank" rel="noopener"><img class="more-glyph" src="/brand/motif-r.svg" alt="" aria-hidden="true" loading="lazy" /><span class="eyebrow">INSTAGRAM</span><span class="more-title">Další kousky<br />a novinky</span><span class="more-handle">@mrpjcz <span aria-hidden="true">↗</span></span><span class="sr-only"> (otevře se v novém okně)</span></a></div></section>
  <section class="studio-band" aria-labelledby="studio-title"><figure class="container"><img src="/images/mrpj-dilna-1200.webp" srcset="/images/mrpj-dilna-1200.webp 1200w, /images/mrpj-dilna.webp 2048w" sizes="(min-width: 1024px) min(1280px, 100vw - 128px), 100vw" alt="Svíčky MRPJ s dřevěnými knoty vyfocené shora" width="2048" height="1536" loading="lazy" /><figcaption><span class="eyebrow">Z NAŠÍ DÍLNY</span><span id="studio-title">Dřevěný knot, vosk a trocha trpělivosti.</span></figcaption></figure></section>
  <section id="pribeh" class="story" aria-labelledby="story-title"><img class="story-line" src="/brand/motif-j.svg" alt="" aria-hidden="true" loading="lazy" /><div class="container story-grid"><div class="story-copy"><p class="eyebrow">02 / NAŠE RUCE. NÁŠ RUKOPIS.</p><h2 id="story-title">Začíná to nápadem.<br />Končí to u tebe.</h2><p>MRPJ je naše rodinná značka svíček a designových nádob. Baví nás projít celou cestu — od tvaru nádoby a výběru barev až po nalévání sójového vosku.</p><p>Někdy vznikne jemný pastel, jindy mramorová kresba nebo výrazná barva. Společné mají jedno: naše ruce a radost z tvoření.</p><p class="editorial">Malé věci.<br />Osobní vztah.</p><a class="text-link" href="#kontakt">Poznejme se ${arrow}</a></div><figure class="story-visual"><span class="reel-frame"><video class="reel" src="/images/mrpj-reel-vyroba.mp4" poster="/images/mrpj-reel-vyroba.webp" width="540" height="960" muted loop playsinline preload="none" controls aria-label="Video z výroby MRPJ: nalévání barevné směsi do forem, odformování a hotové nádoby"></video></span><figcaption>Z NAŠÍ DÍLNY / REEL @MRPJCZ</figcaption></figure></div></section>
  <section id="cteni" class="reading section container" aria-labelledby="reading-title"><div class="section-heading"><p class="eyebrow">03 / MALÉ ČTENÍ</p><h2 id="reading-title">Ke svíčce patří<br />i trocha péče.</h2><p>O materiálu, dřevěném knotu a chvílích s plamenem. Všechno důležité najdeš přímo tady u nás.</p></div><div class="reading-grid">${articles.map(articleCard).join('')}</div></section>
  <section id="faq" class="faq section container" aria-labelledby="faq-title"><div class="faq-intro"><p class="eyebrow">04 / DOBRÉ VĚDĚT</p><h2 id="faq-title">Možná tě<br />zajímá…</h2><p>Pár odpovědí, než si zapálíš.</p></div><div class="faq-list">${faq.map(item => `<details><summary>${item.question}<span aria-hidden="true">+</span></summary><div class="faq-answer"><p>${item.answer}</p><a class="text-link" href="${item.link}">${item.label} ${arrow}</a></div></details>`).join('')}</div></section>
  </main><dialog id="photo-dialog" aria-labelledby="photo-title"><div class="dialog-heading"><div><p class="eyebrow">VLASTNÍ TVORBA MRPJ</p><h2 id="photo-title">Fotografie MRPJ</h2></div><button class="icon-button" id="close-dialog" type="button" autofocus aria-label="Zavřít fotografii">×</button></div><img id="dialog-photo" alt="" /><p class="dialog-caption">Z naší rodinné tvorby.</p></dialog>` });
}
