import { documentPage, articleCard, arrow } from './site.mjs';

export function homePage(logo, articles) {
  const products = [
    { file: 'mrpj-mramor.webp', width: 361, title: 'Mramorování', text: 'Kresba, která se neopakuje.', alt: 'Mramorovaná žebrovaná svíčka MRPJ s víčkem' },
    { file: 'mrpj-pastel.webp', width: 360, title: 'Pastelové tóny', text: 'Jemná barva. Výrazný tvar.', alt: 'Zelená a růžová žebrovaná nádoba MRPJ' },
    { file: 'mrpj-barvy.webp', width: 513, title: 'Hra barev', text: 'Malý detail pro každý den.', alt: 'Výběr barevných svíček a nádob MRPJ ve dvou fotografiích' },
  ];
  return documentPage({ home: true, title: 'MRPJ — Svíčky a nádoby s vlastním rukopisem', description: 'Rodinná tvorba MRPJ. Ručně vyráběné nádoby, svíčky ze sójového vosku a vlastní rukopis. Poznej naši tvorbu i péči o svíčky.', body: `<main id="obsah" tabindex="-1">
  <section class="hero container" aria-labelledby="hero-title"><div class="hero-kicker"><p class="eyebrow">RODINNÁ TVORBA / SÓJOVÉ SVÍČKY</p><span class="eyebrow">Z MALÝCH DETAILŮ</span></div><div class="hero-mark">${logo}</div><div class="hero-bottom"><h1 id="hero-title">Z jedné linky.<br />Do tvého domova.</h1><div class="hero-copy"><p>Svíčky ze sójového vosku a ručně vyráběné nádoby. Tvoříme věci, které mají svůj tvar, barvu a vlastní rukopis.</p><a class="button primary" href="#svicky">Objev naši tvorbu <span aria-hidden="true">↓</span></a></div><figure class="hero-object"><img src="/images/mrpj-mramor.webp" alt="Mramorovaná svíčka MRPJ" width="361" height="640" fetchpriority="high" /><figcaption>JEDEN Z NAŠICH KOUSKŮ</figcaption></figure></div><div class="hero-footnote"><span>Ručně od nádoby po svíčku.</span><a href="#svicky" aria-label="Přejít na naši tvorbu">POKRAČUJ NÍŽ ↓</a></div></section>
  <section id="svicky" class="collection section container" aria-labelledby="collection-title"><div class="section-heading"><p class="eyebrow">01 / TVORBA MRPJ</p><h2 id="collection-title">Každý kousek<br />má svou linku.</h2><p>Jednou jemná, podruhé nepravidelná. V barvě, kresbě i tvaru hledáme to, co dělá naše výrobky našimi.</p></div><div class="collection-grid">${products.map((product, i) => `<figure class="collection-card"><a class="photo-link" href="/images/${product.file}" data-photo="${product.file}" data-title="${product.title}" aria-label="Prohlédnout fotografii: ${product.title}"><span class="photo-image"><img src="/images/${product.file}" alt="${product.alt}" width="${product.width}" height="640" loading="lazy" /></span><span class="photo-action"><span>0${i + 1} / PROHLÉDNOUT</span><span aria-hidden="true">+</span></span></a><figcaption><h3>${product.title}</h3><p>${product.text}</p></figcaption></figure>`).join('')}</div></section>
  <section id="pribeh" class="story" aria-labelledby="story-title"><img class="story-line" src="/brand/motif-j.svg" alt="" aria-hidden="true" loading="lazy" /><div class="container story-grid"><div class="story-copy"><p class="eyebrow">02 / NAŠE RUCE. NÁŠ RUKOPIS.</p><h2 id="story-title">Začíná to nápadem.<br />Končí to u tebe.</h2><p>MRPJ je naše rodinná značka svíček a designových nádob. Baví nás projít celou cestu — od tvaru nádoby a výběru barev až po nalévání sójového vosku.</p><p>Někdy vznikne jemný pastel, jindy mramorová kresba nebo výrazná barva. Společné mají jedno: naše ruce a radost z tvoření.</p><p class="editorial">Malé věci.<br />Osobní vztah.</p><a class="text-link" href="#kontakt">Poznejme se ${arrow}</a></div><figure class="story-visual"><img src="/images/mrpj-vyroba.webp" alt="Nalévání vosku při skutečné výrobě MRPJ" width="360" height="640" loading="lazy" /><figcaption>POHLED DO NAŠÍ VÝROBY / MRPJ</figcaption></figure></div></section>
  <section id="cteni" class="reading section container" aria-labelledby="reading-title"><div class="section-heading"><p class="eyebrow">03 / MALÉ ČTENÍ</p><h2 id="reading-title">Ke svíčce patří<br />i trocha péče.</h2><p>O materiálu, dřevěném knotu a chvílích s plamenem. Všechno důležité najdeš přímo tady u nás.</p></div><div class="reading-grid">${articles.map(articleCard).join('')}</div></section>
  <section id="kontakt" class="contact" aria-labelledby="contact-title"><img class="contact-line" src="/brand/motif-p.svg" alt="" aria-hidden="true" loading="lazy" /><div class="container contact-grid"><div><p class="eyebrow">04 / NAPIŠ NÁM</p><h2 id="contact-title">Další linka<br />může být tvoje.</h2></div><div class="contact-copy"><p>Zaujal tě některý kousek, chceš se na něco zeptat nebo poradit s péčí o svíčku? Budeme rádi, když se ozveš.</p><a class="contact-mail" href="mailto:ahoj@mrpj.cz">ahoj@mrpj.cz ${arrow}</a><p class="contact-note">Na Instagramu nás najdeš jako <strong>@mrpjcz</strong>.</p></div></div></section>
  </main><dialog id="photo-dialog" aria-labelledby="photo-title"><div class="dialog-heading"><div><p class="eyebrow">VLASTNÍ TVORBA MRPJ</p><h2 id="photo-title">Fotografie MRPJ</h2></div><button class="icon-button" id="close-dialog" type="button" autofocus aria-label="Zavřít fotografii">×</button></div><img id="dialog-photo" alt="" /><p class="dialog-caption">Z naší rodinné tvorby.</p></dialog>` });
}
